### ISSUE TITLE
Question: Is TCP or UDP used to write stats in pipelines ?

### ISSUE THREAD

**Issue by gr790** [sentient/statsdbeat#5]
Hello,

I need above clarification. statsd uses UDP to send packets to statsdbeat, but what statsdbeat uses to send packets to logstash pipelines ? 
What changes are required to support TCP if not already implemented. 
What happens to stats which couldn't write into pipeline because of network Issues ? I guess you don't accumulate and retry.

Thanks,
Rahul.

**Comment by sentient** [comment]
It indeed uses UDP to receive the messages. 

The messages are send from statsdbeat to elasticseach via TCP

In the /etc/statsdbeat/statsdbeat.yml file you configure the output

e.g.

output.elasticsearch:  
  hosts: 'http://localhost:9200'

and obviously not localhost. 
So the same what you do for your metricbeat or filebeat 


For retry logic you can configure a queue.spool.
See https://www.elastic.co/guide/en/beats/filebeat/master/configuring-internal-queue.html

Statsdbeat uses the same beat framework. So these internals are all available to you
